apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: https://github.com/Akash-879/myapp-k8s-config.git
      type: git
      name: myapp-repo
